plugins:
  - jekyll-remote-theme
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: Ethan Silver
color-scheme: auto
# logo: (https://images.weserv.nl/?url=https://raw.githubusercontent.com/esilver01/esilver01.github.io/main/IMG_1564.jpg&w=300&h=300&fit=cover&mask=circle&a=top)
logo:  IMG_1564.jpg
navigation: 
  - name: CV
#     link: ./index.html
